"""add version column for optimistic locking

Revision ID: d6b9703b9c35
Revises: 97e68b588a7c
Create Date: 2026-09-04 11:48:10.851551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6b9703b9c35'
down_revision: Union[str, None] = '97e68b588a7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'version')
    # ### end Alembic commands ###
